Fix DatatransferObjectTest for Python 3.12
This fixes a test error when run with Python 3.12:
```
Traceback (most recent call last):
  File "pcs_test/tier0/common/interface/test_dto.py", line 41, in test_has_all_subclasses_are_dataclasses
    _import_all(pcs.__path__)
  File "pcs_test/tier0/common/interface/test_dto.py", line 31, in _import_all
    loader.find_module(module_name).load_module(module_name)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```
Instead, use the spec-based APIs introduced in 3.4:

https://docs.python.org/3.12/library/importlib.html#importlib.machinery.FileFinder
https://docs.python.org/3.12/library/importlib.html#importlib.machinery.ModuleSpec

v2: rename the first member of the ModuleInfo tuple returned by
pkgutil.walk_packages to avoid ambiguities.